<?php

use yii\helpers\Html;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Solicitudes;
use app\models\Estatus1;
use app\models\Estatus2;
use app\models\Estatus3;
use app\models\Trabajador;
use kartik\grid\GridView;
use kartik\mpdf\Pdf;
use app\models\Users;
use app\models\Areas;
use app\models\Presupuestos;
use app\models\Gestion;
use app\models\Departamentos;
use app\models\Recepciones;
use yii\widgets\ActiveForm;
use yii\web\JsExpression;
use yii\helpers\Url;
use kartik\depdrop\DepDrop;



$defaultExportConfig = [
    GridView::TEXT => [
        'label' => 'Exportar a Formato TXT',
        'iconOptions' => ['class' => 'text-muted'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => 'grid-export',
        'alertMsg' => 'The TEXT export file will be generated for download.',
        'options' => ['title' => 'Tab Delimited Text'],
        'mime' => 'text/plain',
        'config' => [
            'colDelimiter' => "\t",
            'rowDelimiter' => "\r\n",
        ]
    ],
    GridView::EXCEL => [
        'label' => 'Exportar a Excel',
        'iconOptions' => ['class' => 'text-success'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => 'Gestiones',
        'alertMsg' => 'The EXCEL export file will be generated for download.',
        'options' => ['title' => 'Microsoft Excel 95+'],
        'mime' => 'application/vnd.ms-excel',
        'config' => [
            'worksheet' => 'ExportWorksheet',
            'cssFile' => ''
        ]
    ],
    GridView::PDF => [
        'label' => 'Exportar a PDF',
        'iconOptions' => ['class' => 'text-danger'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => 'Gestiones',
        'alertMsg' => 'El Reporte de Gestiones será generado',
        'options' => ['title' => 'Portable Document Format'],
        'mime' => 'application/pdf',
        'config' => [
            'mode' => 'c',
            'format' => 'Letter',
            'destination' => 'I', 
            'orientation' => 'L',
            'marginTop' => 20,
            'marginBottom' => 20,
            'cssInline' => '.kv-wrap{padding:20px;}' .
                '.kv-align-center{text-align:center;font-size:10 px;}' .
                '.kv-grid-table{font-size:10 px;}'.
                '.kv-align-left{text-align:left;}' .
                '.kv-align-right{text-align:right;}' .
                '.kv-align-top{vertical-align:top!important;}' .
                '.kv-align-bottom{vertical-align:bottom!important;}' .
                '.kv-align-middle{vertical-align:middle!important;font-size:10 px;}' .
                '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-caption{font-size:0.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
            'methods' => [
                'SetHeader'=>['<center><h1>Envio</h1></center>'], 
                'SetFooter'=>['{PAGENO}'],
            ],
            'options' => [
                'title' => $this->title,
                'subject' => 'PDF export generated by kartik-v/yii2-grid extension',
                'keywords' => 'krajee, grid, export, yii2-grid, pdf',
            ],
//            'contentBefore'=>'',
//            'contentAfter'=>''
        ]
    ],

];

?>

<!-- Aqui empieza el Div del Form de la Busqueda -->
<center>
    <div class="container center-block">
	<div class="col-lg-12">
			<div class="box-header center-block">
                            <h3 class="display-3 center-block">
					Cambio de Estatus y Envio de MEMO					
                            </h3>
			</div>
        </div>
    </div>


<!--Para el Origen de los Memos -->    
    
<div class="container center-block">
	<div class="col-lg-6 col-md-6">
                        <div class="sepingresa-form col-lg-8 col-md-8 col-md-offset-2 col-lg-offset-2">

    <?php $form = ActiveForm::begin(); ?>
                            
    <?= $form->field($modelorigenmemo, 'departamento')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Departamentos::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione el Departamento'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]);
            
    ?>

    <?= $form->field($modelorigenmemo, 'unidad')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Recepciones::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione la Unidad'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]); 
            
    ?>

     <?=
    /* Estatus 1 con Select2 de kartik*/
        $form->field($modelorigenmemo, 'estatus1')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Estatus1::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione el Estatus Nivel 1'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]);
    
    ?>
    
    
    <?php
    /* Estatus 2 con depdrop de kartik*/
    echo $form->field($modelorigenmemo, 'estatus2')->widget(DepDrop::classname(), [
    'data' => ArrayHelper::map(Estatus2::find()->orderBy('nombre')->all(), 'id', 'nombre'),
    'type'=>DepDrop::TYPE_SELECT2,
    'options'=>['id'=>'estatus2_id', 'placeholder'=>'Seleccione el Estatus Nivel 2'],
    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
    'pluginOptions'=>[
        'placeholder' => 'Seleccione el Estatus Nivel 2',
        'depends'=>['origenmemo-estatus1'],
        'url'=>Url::to(['/estatus3/estatus1']),
    ]
    ]);
        
    ?>

    <?=
    /* Estatus 3 con depdrop de kartik*/
    $form->field($modelorigenmemo, 'estatus3')->widget(DepDrop::classname(), [
    'data' => ArrayHelper::map(Estatus3::find()->orderBy('nombre')->all(), 'id', 'nombre'),
    'type'=>DepDrop::TYPE_SELECT2,
    'options'=>['id'=>'estatus3_id', 'placeholder'=>'Seleccione el Estatus Nivel 3'],
    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
    'pluginOptions'=>[
        'placeholder' => 'Seleccione el Estatus Nivel 3',
        'depends'=>['estatus2_id'],
        'url'=>Url::to(['/estatus3/estatus2']),
    ]
    ]);
    ?>      
    
    

   
    <div class="col-lg-4 col-md-4 col-lg-offset-4 col-md-offset-4">
                        <?= Html::submitButton('Cargar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    </div>
                        
    </div>
    
    <!--Para el Envio de los Memos -->    
    
<div class="container center-block">
	<div class="col-lg-6 col-md-6">
                        <div class="final-form col-lg-8 col-md-8 col-md-offset-2 col-lg-offset-2">
<!-- Formulario para cambio de Estatus de Varias Items a la Vez-->
<?=Html::beginForm(['cambioestatusgeneromemo'],'post');?>
    
<!-- Formulario del Form modelfinalmemo-->     
    <?php// $form = ActiveForm::begin(); ?>
                            
    <?= $form->field($modelfinalmemo, 'departamentofinal')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Departamentos::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione el Departamento'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]);
            
    ?>

    <?= $form->field($modelfinalmemo, 'unidadfinal')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Recepciones::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione la Unidad'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]); 
            
    ?>

     <?=
    /* Estatus 1 con Select2 de kartik*/
        $form->field($modelfinalmemo, 'estatus1final')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Estatus1::find()->orderBy('nombre')->all(), 'id', 'nombre'),
        'language' => 'es',
        'options' => ['placeholder' => 'Seleccione el Estatus Nivel 1'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]);
    
    ?>
    
    
    <?php
    /* Estatus 2 con depdrop de kartik*/
    echo $form->field($modelfinalmemo, 'estatus2final')->widget(DepDrop::classname(), [
    'data' => ArrayHelper::map(Estatus2::find()->orderBy('nombre')->all(), 'id', 'nombre'),
    'type'=>DepDrop::TYPE_SELECT2,
    'options'=>['id'=>'estatus2_idfinal', 'placeholder'=>'Seleccione el Estatus Nivel 2'],
    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
    'pluginOptions'=>[
        'placeholder' => 'Seleccione el Estatus Nivel 2',
        'depends'=>['finalmemo-estatus1final'],
        'url'=>Url::to(['/estatus3/estatus1']),
    ]
    ]);
        
    ?>

    <?=
    /* Estatus 3 con depdrop de kartik*/
    $form->field($modelfinalmemo, 'estatus3final')->widget(DepDrop::classname(), [
    'data' => ArrayHelper::map(Estatus3::find()->orderBy('nombre')->all(), 'id', 'nombre'),
    'type'=>DepDrop::TYPE_SELECT2,
    'options'=>['id'=>'estatus3_idfinal', 'placeholder'=>'Seleccione el Estatus Nivel 3'],
    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
    'pluginOptions'=>[
        'placeholder' => 'Seleccione el Estatus Nivel 3',
        'depends'=>['estatus2_idfinal'],
        'url'=>Url::to(['/estatus3/estatus2']),
    ]
    ]);
    ?>      
    
    

   
    <div class="col-lg-8 col-md-8 col-lg-offset-2 col-md-offset-2">
                        <?php //echo Html::submitButton('Enviar Memorandum', ['class' => 'btn btn-info']) ?>
    </div>
<!-- Formulario del Modelo -->
    <?php //ActiveForm::end(); ?>

                            
<?= Html::submitButton('<span class="glyphicon glyphicon-floppy-saved"></span> Enviar Memorandum', ['class' => 'btn btn-primary btn-lg']) ?>                            
    </div>
                        
    </div>
    
</div>
</center>

<!-- Termina el Formulario de la Busqueda -->

<?php     
    $columns = [
            [
            'class'=>'kartik\grid\CheckboxColumn',
            'headerOptions'=>['class'=>'kartik-sheet-style'],
            'rowSelectedClass' => GridView::TYPE_INFO,
            'checkboxOptions' => function($model) {
                return ['value' => $model->id];
            },
            ],
            'id',
        
            [
            'class'=>'kartik\grid\SerialColumn',
            'contentOptions'=>['class'=>'kartik-sheet-style'],
            'width'=>'36px',
            'header'=>'',
            'headerOptions'=>['class'=>'kartik-sheet-style'],
            ],
          
            [
            'class'=>'kartik\grid\ExpandRowColumn',
            'width'=>'50px',
            'value'=>function ($model, $key, $index, $column) {
                return GridView::ROW_COLLAPSED;
            },
            'detail'=>function ($model, $key, $index, $column) {
                return Yii::$app->controller->renderPartial('_form', ['model'=>$model]);
            },
            'headerOptions'=>['class'=>'kartik-sheet-style'],
            'expandOneOnly'=>true,
            ],

            [
            'attribute' => 'solicitud_id',
            'value' => 'num_solicitud',
            'label' => 'N°<br>Solicitud',
            'encodeLabel' => false,
            'format' => 'text',
            ],
                    
            [
            'attribute' => 'requerimiento',
            'value' => 'requerimiento',
            'format' => 'text',
            ],
                    
            [
            'attribute' => 'iddoc',
            'value' => 'iddoc',
            'format' => 'text',
            ],
            
            [
            'attribute' => 'fechaingreso',
            'value' => 'fechaingreso',
            'format' => 'text',
            'label' => 'Fecha<br>Ingreso',
            'format' => 'text',
            'encodeLabel' => false,
            ],
            
            [
            'attribute' => 'fechaultimamodificacion',
            'value' => 'fechaultimamodificacion',
            'label' => 'Fecha<br>Modificación',
            'format' => 'text',
            'encodeLabel' => false,
            ],
        
            [ 
            'attribute' => 'beneficiario', 				
            'value' => 'beneficiario', 
            'format' => 'text', 
            ],
        
            [ 
            'attribute' => 'cibeneficiario', 				
            'value' => 'cibeneficiario', 
            'format' => 'text', 
            ],
        
            [                     
            'attribute' => 'edadbeneficiario', 			
            'value' => 'edadbeneficiario', 
            'format' => 'text',
            'visible'=> false,
            ],
        
            [                     
            'attribute' => 'telefono', 			
            'value' => 'telefono', 
            'format' => 'text',
            'visible'=> false,
            ],
                   
            [ 
            'attribute' => 'empresaoinstitucion', 		
            'value' => 'empresaoinstitucion',
            'label' => 'Empresa<br>Casa Comercial',
            'format' => 'text',
            'encodeLabel' => false,
            ],
            
            [ 
            'attribute' => 'rif', 		
            'value' => 'rif', 
            'format' => 'text',
            ],
     
            [ 
            'attribute' => 'cantidad', 						
            'value' => 'cantidad',
            'label' => 'N°',
            'format' => 'text',
            //'visible'=> false,
            ],
            
            [ 
            'attribute' => 'orpa', 						
            'value' => 'orpa', 
            'format' => 'text',
            'visible'=> false,
            ],

                    
            [ 
            'attribute' => 'cheque', 						
            'value' => 'cheque', 
            'format' => 'text',
            'visible'=> false,
            ],
                    
                       
        
            [ 
            'attribute' => 'monto', 						
            'value' => 'monto', 
            'hAlign'=>'right', 
            'vAlign'=>'middle',
            'width'=>'100px',
            'format'=>'currency',
            'pageSummary'=>true,
            ],
            
            //[
            //'class'=>'kartik\grid\ActionColumn',
            //],
            
        ];

?>

<?php
    echo GridView::widget([
        'id'=>'kv-grid-gestiona',
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,
        'columns'=>$columns,
        'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
        'headerRowOptions'=>['class'=>'kartik-sheet-style'],
        'filterRowOptions'=>['class'=>'kartik-sheet-style'],
        'pjax'=>true, // pjax is set to always true for this demo
        // set your toolbar
//        'toolbar'=> [
//            ['content'=>
//                Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-gestion'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=>'Reset Grid'])
//            ],
//            '{export}',
//            '{toggleData}'
//        ],
        // set export properties
        'export'=>[
            'fontAwesome'=>true
        ],
        // parameters from the demo form
        'bordered'=>true,
        'striped'=>true,
        'condensed'=>true,
        'responsive'=>true,
        'hover'=>true,
        'showPageSummary'=>true,
//        'panel'=>[
//            'type'=>GridView::TYPE_INFO,
//            'heading'=>'<center><i class="glyphicon glyphicon-eye-open"></i>Cambio de Estatus<i class="glyphicon glyphicon-eye-open"></i>'
//            . '</center>',
//        ],
        'persistResize'=>false,
        'toggleDataOptions'=>['minCount'=>10],
        'exportConfig'=>$defaultExportConfig,
    ]);

?>
<!-- Termina el GridView empieza el Envio de Información -->

<?= Html::endForm();?> 

<!-- Fin del Formulario -->


</div>
